### ISSUE TITLE
RTC Accessibility User Requirements

### ISSUE THREAD

**Issue by pes10k** [w3cping/privacy-reviews#3]
Spec - https://w3c.github.io/apa/raur/

**Comment by NalaGinrut** [comment]
This privacy review is a little different since it's not a specific issue review. The RTC Accessibility User Requirements document not a specific API description. So the plan is to check specific features of the API which is described in this document.

It may not be a fast review. I'll update each time I finish a review.

**Comment by pes10k** [comment]
understood, thanks!

**Comment by NalaGinrut** [comment]
Here're the related review and the result.  `Nothing` means no notable things need to be reviewed.

- [ ] [WebRTC DSCP Control API](https://w3c.github.io/webrtc-priority/)  -- `Nothing`

- [ ] [WebRTC 1.0: Real-time Communication Between Browsers](https://www.w3.org/TR/webrtc/) -- `Reviewing`

- [ ] [Identifiers for WebRTC's Statistics API](https://w3c.github.io/webrtc-stats/) -- See results

**Comment by NalaGinrut** [comment]
**Identifiers for WebRTC's Statistics API** 

1. The statistics may contain privacy-sensitive information. The good part is that the result of `getStats()` is recommended not to be reused after deleted. However, it's better to suggest clean the cache after it's deleted explicitly. Although the current description is to prevent `getStats()` return status from `monitored object`, I don't think it's enough, since the cache (iff the implementation does it) must be cleaned immediately after delete.

2.

**Comment by pes10k** [comment]
hi @NalaGinrut thank you very much for all this!  I think you've gone above and beyond!  But the only item that needs to be reviewed here is the "Accessibility User Requirements" document; the entire WebRTC spec (which is enormous!) doesn't need another review.  Just to save you some time :)

**Comment by NalaGinrut** [comment]
@pes10k OK, thanks for mention. Is `rtc statistics API` reviewed before?

**Comment by pes10k** [comment]
It has been, but not in a while I believe.  I expect we'll / PING will be asked to review again soon, as the WebRTC folks want to transition soon. So, that work here is terrific, just ahead of the curve :)

**Comment by NalaGinrut** [comment]
RAUR is fine for privacy concerns since it's only requirements definition. I've reviewed some specific APIs related to it. Now I think it's OK to close as passed.

**Comment by sandandsnow** [comment]
Closing issue as the review has been undertaken.

(Note: there may still be outstanding privacy considerations identified in the review that have not yet been resolved. See https://github.com/w3cping/tracking-issues/issues)
